In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

bug_vector=np.array([1,0.9,5,120])
scaled_vector = bug_vector/np.max(bug_vector)
print(scaled_vector)


[0.00833333 0.0075     0.04166667 1.        ]


In [2]:
import numpy as np

# A single data point (Bug Report: [Severity, Reproducibility, Steps, Time])
bug_vector = np.array([1, 0.9, 5, 120])

# We can easily do math on it!
# For example, normalize the "Time" feature if we want to scale our data
scaled_vector = bug_vector / np.max(bug_vector)

print(f"Original: {bug_vector}")
print(f"Scaled:   {scaled_vector}")

Original: [  1.    0.9   5.  120. ]
Scaled:   [0.00833333 0.0075     0.04166667 1.        ]


In [33]:
np.random.seed(42)
a=np.random.randint([[1,8],[1,19],[3,9]])

In [34]:
a

array([[ 0,  6],
       [ 0, 14],
       [ 2,  7]], dtype=int32)

In [35]:

b=np.random.randint([[2,5],[2,7],[3,6]])

In [36]:
print(f"Original A:\n {a}"
      f"\nOrginal b:\n {b}")

Original A:
 [[ 0  6]
 [ 0 14]
 [ 2  7]]
Orginal b:
 [[0 4]
 [0 1]
 [2 2]]


In [37]:
a+b

array([[ 0, 10],
       [ 0, 15],
       [ 4,  9]], dtype=int32)

In [38]:
a*b

array([[ 0, 24],
       [ 0, 14],
       [ 4, 14]], dtype=int32)

In [40]:
a.T

array([[ 0,  0,  2],
       [ 6, 14,  7]], dtype=int32)

In [41]:
import numpy as np

# Feature vector for a Field Task
features = np.array([2.0, 15.0, 4.0]) # [Traffic, Distance, Complexity]

# Weights learned by your model
weights = np.array([0.5, 0.2, 0.3])

# The Dot Product: Prediction Calculation
prediction = features @ weights

print(f"Predicted Time: {prediction} hours")

Predicted Time: 5.2 hours
