what is numpy ? and why it is faster than list? or why we do not use list ?
ANS - numpy is an liabrabry in python name as numeric python , numpy works with large data collection with very fast speed than list
it is faster than list because  -

1.in list there are multiples types like string , int , float so whenever the list check fro the next element it have to check
its type as well but numpy have fixed data type so it skips the type checking

2.in list the elemts are stratted everywhere in ram so to go to next element the CPU have to jump to next element whihc takes time
but in numpy it is written side by side

3.vectorization - python needs for loops to perform math on each element but numpy work with vectorization which do the all
options at once which saves time.

ndim	= The number of Dimensions (axes). = 	A list is 1D; a table is 2D; a cube is 3D.<br>
shape	= A tuple showing the size of each dimension. = 	A table with 5 rows and 3 columns has a shape of (5, 3).<br>
size	= Total number of elements in the array. =	For a (5, 3) array, the size is 15.<br>
dtype	= The Data Type of the elements.	= int64, float32, etc. (Remember: all must be the same!)<br>

In [9]:
import numpy as np
a=[1,2,3,45,6]
a[2::2]

[3, 6]

In [10]:
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr[0::2]

[0, 2, 4, 6, 8]

In [25]:

a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a.ndim

2

In [40]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [44]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
a=np.arange(0,13,0.5)

In [68]:
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5])

In [65]:
np.linspace(0,12,24)

array([ 0.        ,  0.52173913,  1.04347826,  1.56521739,  2.08695652,
        2.60869565,  3.13043478,  3.65217391,  4.17391304,  4.69565217,
        5.2173913 ,  5.73913043,  6.26086957,  6.7826087 ,  7.30434783,
        7.82608696,  8.34782609,  8.86956522,  9.39130435,  9.91304348,
       10.43478261, 10.95652174, 11.47826087, 12.        ])

In [69]:
scores = np.array([10, 20, 30])

In [70]:
scores+5

array([15, 25, 35])

In [71]:
a=np.array([[1,2,3],[4,5,6]])

In [72]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
a[:1,:1]

array([[1]])

In [88]:
a[:,0]

array([1, 4])