In [38]:
#reverse a list
l =[1,2,3,4,5,65,6]
print(l[::-1])

a="jayesh"
b=""
for i in a:
    b=i+b
print(b)


[6, 65, 5, 4, 3, 2, 1]
hseyaj


In [41]:
from collections import Counter
l =[1,2,3,4,5,65,6,4]
a=Counter(l)
a


Counter({4: 2, 1: 1, 2: 1, 3: 1, 5: 1, 65: 1, 6: 1})

In [48]:
#Find second largest number
first_max=max(l)
second_max=max(n for n in l if n!=first_max)
second_max

6

In [67]:
#Create array and reshape
import numpy as np
a=np.random.randint(1,30,10)
print(a)
b=np.random.randint(1,23,10)
print(b)

[22 20  3 27 25 19  7 19  4 27]
[19  9 17 19  5  7 11  4  3 19]


In [68]:
np.mean(a)

np.float64(17.3)

In [69]:
np.median(a)

np.float64(19.5)

In [71]:
a@b

np.int32(2098)

In [72]:
np.dot(a,b)

np.int32(2098)

In [78]:
#Transpose matrix
np.random.seed(42)
a=np.random.randint(1,30,size=(2,2))
a

array([[ 7, 20],
       [29, 15]], dtype=int32)

In [79]:
a.T

array([[ 7, 29],
       [20, 15]], dtype=int32)